worker_processes 1;

events {
    worker_connections 1024;
}

http {
    include /opt/homebrew/etc/nginx/mime.types;
    default_type application/octet-stream;

    sendfile on;
    keepalive_timeout 65;

    upstream backends {
        server 10.7.6.20:3001;
        server 10.7.3.188:3002;
    }

    server {
        listen 8080;
        server_name localhost;

        location / {
            proxy_pass http://backends;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }

    server {
        listen 8443 ssl;

        server_name app.teambyte.test api.teambyte.test;

        ssl_certificate /opt/homebrew/etc/nginx/certs/teambyte.crt;
        ssl_certificate_key /opt/homebrew/etc/nginx/certs/teambyte.key;

        location / {
            proxy_pass http://backends;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}
